[ 2019-01-20 16:40:35 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 221, in start
    callback()
  File "alexa.py", line 55, in <lambda>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_messy/main.py", line 63, in main
    volume.play_prompt(alexa_said)
  File "/opt/MessyPi/yuyin/alexa/func_messy/volume.py", line 96, in play_prompt
    pygame.mixer.music.play(loop=0)
TypeError: 'loop' is an invalid keyword argument for this function

[ 2019-01-20 17:10:39 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 221, in start
    callback()
  File "alexa.py", line 55, in <lambda>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_messy/main.py", line 40, in main
    volume_in = volume.volume(p)
  File "/opt/MessyPi/yuyin/alexa/func_messy/volume.py", line 54, in volume
    temp_in = volume_hasbeen()
  File "/opt/MessyPi/yuyin/alexa/func_messy/volume.py", line 35, in volume_hasbeen
    data = stream.read(CHUNK)
UnboundLocalError: local variable 'stream' referenced before assignment

[ 2019-01-20 17:12:08 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 221, in start
    callback()
  File "alexa.py", line 55, in <lambda>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_messy/main.py", line 40, in main
    volume_in = volume.volume(p)
  File "/opt/MessyPi/yuyin/alexa/func_messy/volume.py", line 54, in volume
    temp_in = volume_hasbeen()
  File "/opt/MessyPi/yuyin/alexa/func_messy/volume.py", line 34, in volume_hasbeen
    stream = p.open(format=FORMAT,
NameError: name 'p' is not defined

[ 2019-01-20 17:12:38 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 221, in start
    callback()
  File "alexa.py", line 55, in <lambda>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_messy/main.py", line 40, in main
    volume_in = volume.volume(p)
  File "/opt/MessyPi/yuyin/alexa/func_messy/volume.py", line 54, in volume
    temp_in = volume_hasbeen(p)
  File "/opt/MessyPi/yuyin/alexa/func_messy/volume.py", line 41, in volume_hasbeen
    frames.append(data)
NameError: name 'frames' is not defined

[ 2019-01-20 17:13:38 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 221, in start
    callback()
  File "alexa.py", line 55, in <lambda>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_messy/main.py", line 40, in main
    volume_in = volume.volume(p)
  File "/opt/MessyPi/yuyin/alexa/func_messy/volume.py", line 63, in volume
    if temp > FAZHI:
NameError: name 'temp' is not defined

[ 2019-01-20 17:22:48 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 221, in start
    callback()
  File "alexa.py", line 55, in <lambda>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_messy/main.py", line 39, in main
    volume_in = volume.volume(p)
  File "/opt/MessyPi/yuyin/alexa/func_messy/volume.py", line 51, in volume
    temp_in = volume_hasbeen(p,frames)
  File "/opt/MessyPi/yuyin/alexa/func_messy/volume.py", line 39, in volume_hasbeen
    audio_data = np.fromstring(data, dtype=np.short)
NameError: name 'data' is not defined

[ 2019-01-20 17:23:35 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 221, in start
    callback()
  File "alexa.py", line 55, in <lambda>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_messy/main.py", line 39, in main
    volume_in = volume.volume(p)
  File "/opt/MessyPi/yuyin/alexa/func_messy/volume.py", line 53, in volume
    temp_in = volume_hasbeen(p,frames)[0]
  File "/opt/MessyPi/yuyin/alexa/func_messy/volume.py", line 40, in volume_hasbeen
    data = temp_in_stream.read(CHUNK)
NameError: name 'temp_in_stream' is not defined

[ 2019-01-20 17:24:14 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 221, in start
    callback()
  File "alexa.py", line 55, in <lambda>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_messy/main.py", line 39, in main
    volume_in = volume.volume(p)
  File "/opt/MessyPi/yuyin/alexa/func_messy/volume.py", line 53, in volume
    temp_in = volume_hasbeen(p,frames)[0]
  File "/opt/MessyPi/yuyin/alexa/func_messy/volume.py", line 38, in volume_hasbeen
    frames_per_buffer=CHUNK)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 17:26:32 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 17:27:46 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 17:29:12 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 17:30:27 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 17:33:04 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 17:33:38 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 17:37:13 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 17:38:31 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 17:41:00 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 17:49:36 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 221, in start
    callback()
  File "alexa.py", line 55, in <lambda>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_messy/main.py", line 39, in main
    volume_in = volume.volume(p)
  File "/opt/MessyPi/yuyin/alexa/func_messy/volume.py", line 78, in volume
    volume.play_prompt_not_loop(play_ding)
AttributeError: 'function' object has no attribute 'play_prompt_not_loop'

[ 2019-01-20 17:50:09 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 221, in start
    callback()
  File "alexa.py", line 55, in <lambda>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_messy/main.py", line 39, in main
    volume_in = volume.volume(p)
  File "/opt/MessyPi/yuyin/alexa/func_messy/volume.py", line 81, in volume
    data = stream.read(CHUNK)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
OSError: [Errno -9981] Input overflowed

[ 2019-01-20 17:51:32 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 17:55:55 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 17:58:25 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 18:10:36 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 18:12:58 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 18:27:03 ] 
Traceback (most recent call last):
  File "alexa.py", line 37, in <module>
    pygame.mixer.init(frequency=15500, size=-16, channels=4)
pygame.error: No available audio device

[ 2019-01-20 18:27:03 ] 
Traceback (most recent call last):
  File "alexa.py", line 37, in <module>
    pygame.mixer.init(frequency=15500, size=-16, channels=4)
pygame.error: No available audio device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "alexa.py", line 42, in <module>
    exit()
  File "/usr/lib/python3.5/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

[ 2019-01-20 18:28:44 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 18:42:01 ] 
Traceback (most recent call last):
  File "alexa.py", line 37, in <module>
    pygame.mixer.init(frequency=15500, size=-16, channels=4)
pygame.error: No available audio device

[ 2019-01-20 18:42:01 ] 
Traceback (most recent call last):
  File "alexa.py", line 37, in <module>
    pygame.mixer.init(frequency=15500, size=-16, channels=4)
pygame.error: No available audio device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "alexa.py", line 42, in <module>
    exit()
  File "/usr/lib/python3.5/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

[ 2019-01-20 18:42:56 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 18:44:23 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 18:51:09 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 19:28:27 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 19:42:17 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 19:47:40 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 221, in start
    callback()
  File "alexa.py", line 55, in <lambda>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_messy/main.py", line 46, in main
    play_audio_file(none_prompt)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 71, in play_audio_file
    rate=ding_wav.getframerate(), input=False, output=True)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 19:50:37 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 19:58:17 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 20:00:08 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 20:10:49 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 20:11:52 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 20:12:24 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 20:14:52 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 20:22:26 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 20:25:10 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 20:26:11 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 20:29:35 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 20:33:53 ] 
Traceback (most recent call last):
  File "alexa.py", line 55, in <module>
    detector.start(detected_callback=lambda: main.main(p,detector),sleep_time=0.03)
  File "/opt/MessyPi/yuyin/alexa/func_alexa/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

[ 2019-01-20 21:13:55 ] 
Traceback (most recent call last):
  File "alexa.py", line 37, in <module>
    pygame.mixer.init(frequency=15500, size=-16, channels=4)
pygame.error: No available audio device

[ 2019-01-20 21:13:55 ] 
Traceback (most recent call last):
  File "alexa.py", line 37, in <module>
    pygame.mixer.init(frequency=15500, size=-16, channels=4)
pygame.error: No available audio device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "alexa.py", line 42, in <module>
    exit()
  File "/usr/lib/python3.5/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

[ 2019-01-21 09:57:04 ] 
Traceback (most recent call last):
  File "alexa.py", line 37, in <module>
    pygame.mixer.init(frequency=15500, size=-16, channels=4)
pygame.error: No available audio device

